### ISSUE TITLE
Links Under Maintenance

### ISSUE THREAD

**Issue by slavakurilyak** [PardoAlejo/MovieCuts#3]
[Currently the links are under maitenance.](https://github.com/PardoAlejo/MovieCuts#:~:text=Currently%20the%20links%20are%20under%20maitenance) Any updates on this? 🤔

**Comment by PardoAlejo** [comment]
Hi, I forgot to update the README. If you need the data please fill-up this [Google form](https://forms.gle/FUNnZ8wpYRCspTJq9). All the links are working fine now.
